# Generated by Django 3.2.7 on 2025-08-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230216_0521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['rank', '-created_date']},
        ),
    ]
