# Generated by Django 2.2 on 2025-02-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230216_0521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['rank', '-created_date']},
        ),
    ]
